### ISSUE TITLE
Issues installing GWF

### ISSUE THREAD

**Issue by ymer** [mailund/gwf#104]
I'm running into two issues trying to make a new install of GWF

1) "SyntaxError: Non-ASCII character '\xc3' in file setup.py on line 25, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details"

Triggered by "Søndergaard"

2) "byte-compiling build/bdist.linux-x86_64/egg/gwf/backends/base.py to base.pyc
  File "build/bdist.linux-x86_64/egg/gwf/backends/base.py", line 38
    class Backend(metaclass=BackendType):
                           ^
SyntaxError: invalid syntax"

**Comment by dansondergaard** [comment]
We're currently in the midst of a major rewrite and thus the master branch is not usable right now. Right now the new version of gwf only supports Python 3, which causes the errors you see. *Please* only use official releases of gwf (such as the older releases), unless you want to contribute to gwf.

When version 1.0.0 is complete it will be made available through more official channels such as PyPI (i.e. installable through `pip`) which should make installing and upgrading gwf easier.
