### ISSUE TITLE
Update examples

### ISSUE THREAD

**Issue by andreasnoack** [mailund/gwf#123]
It looks like the examples were not updated in https://github.com/mailund/gwf/commit/fc91294df8205e1a7ef00ca5398cde59c083f643.

**Comment by dansondergaard** [comment]
@mailund Spent a few hours trying to update the examples, but I know nothing about bwa and samtools. Could you please update them?

**Comment by mailund** [comment]
I have updated the examples now. They still use the templates and not functions. Let's have a chat about whether they should be changed...
