### ISSUE TITLE
Setting "warn_sink" to False on a target doesn't work

### ISSUE THREAD

**Issue by mailund** [mailund/gwf#138]
That option is not passed along to the `Target` operator from the workflow, as far as I can see.

It really also should be called when the workflow is prepared and not when the target is created if it is needed at all after we make `inputs` and `outputs` mandatory fields. It should be possible to modify the target before getting a warning.

**Comment by dansondergaard** [comment]
Reverted the commit in be41a86. I'll fix this later.

**Comment by dansondergaard** [comment]
No longer relevant after f2d866bb95696.
