### ISSUE TITLE
Traitlets for configuration and argument parsing

### ISSUE THREAD

**Issue by dansondergaard** [mailund/gwf#142]
Should we be using traitslets for configuration?

http://traitlets.readthedocs.io/en/stable/using_traitlets.html

**Comment by mailund** [comment]
If you think we gain something from it... Our current configurations are rather simple but also easy to work with.

**Comment by dansondergaard** [comment]
The more I read about the traitlets library, the more it seems that it would solve quite a few annoying problems in the gwf core and allow for better handling of defaults, configuration of plugins, backends and a at the same time protect against a bunch of different type errors that can completely break gwf with the current configuration handling.

However, the docs are a bit lacking in some aspects (I see no documentation fo the `Application` object), so I'll have to read more into this. However, I think that it will be a worthwhile replacement for `configargparse` which has a multitude of problems and is more-or-less unmaintained.

**Comment by dansondergaard** [comment]
Traitlets would be awesome to use if the argument parsing wasn't to inhuman. E.g. to specify a list of targets to run, the user would have to type:

```
$ gwf run --targets '["Target1", "Target2"]'
```

which is just annoying. Also, it's not possible to avoid the `--targets` option... Traitlets are still really awesome though and I'll try to see if we can use it just for configs, not for argument parsing, since it provides easy and flexible configuration of classes.

**Comment by mailund** [comment]
For configuration files, we could also consider just running Python scripts. This is what shells do, or what Emacs does, and we don't really need a separate language for option files, I guess. General files will just make it a bit harder to update them automatically, I suppose.

**Comment by dansondergaard** [comment]
Traitlet configs are actually just Python code, but with traitlets classes can declare "traits" which are basically just things that can be configured, and the config options are then injected into the appropriate classes automatically. It's pretty sweet, actually :-)
