### ISSUE TITLE
Confusing dots in status output

### ISSUE THREAD

**Issue by dansondergaard** [mailund/gwf#143]
For some reason, a dot is printed after some target names to make the names align with other names. This is confusing (especially when using dots in target names) and should just be a space instead. I doesn't seem possible to change this externally. Does this need to be fixed in the statusbar library, @mailund?

**Comment by mailund** [comment]
I think you can set an option to statusbar, but I will check it later.

**Comment by dansondergaard** [comment]
| can't find any options for that. Can't even really find the place where the dots are added in the statusbar code :-(

**Comment by dansondergaard** [comment]
Depends on https://github.com/mailund/statusbar/pull/5.
