### ISSUE TITLE
Targets never marked as failed

### ISSUE THREAD

**Issue by dansondergaard** [mailund/gwf#144]
Targets that fail are marked as "should run" (which they should), but never failed.

**Comment by mailund** [comment]
Is this an issue with the backend? With qsub I could never get failure info. I think we can with slurm

**Comment by dansondergaard** [comment]
We can't get it directly with SLURM since we can't count on `sacct` being present. Maybe we shouldn't show failed targets at all. It seems to complicate things, even though I'd love to be able to get a list of all failed targets.
