### ISSUE TITLE
Cannot override template options in target

### ISSUE THREAD

**Issue by dansondergaard** [mailund/gwf#145]
When using templates, it's not possible to override the template options in the target because of this line:

https://github.com/mailund/gwf/blob/crazy-refactoring/gwf/core.py#L136

Instead, the two dicts should be merged, and the target dict should take precedence.

**Comment by mailund** [comment]
I used 

```python
self.options.update(options)
```

earlier, but I think with python 3.5 you can use

```python
self.options = {**options, **self.options}
```

The order determines what dict gets preference; I don't have Python 3 installed on my laptop so I cannot check it right now -- and I'm a really poor network so I am not going to download it -- but you can quickly do that.

**Comment by dansondergaard** [comment]
Both are fine, `update` is shorter. Don't know how I could've missed it earlier, but I never used templates much until now.
