### ISSUE TITLE
Pipe logs to less

### ISSUE THREAD

**Issue by micknudsen** [mailund/gwf#150]
Not really sure what is causing this, but when I pipe logs to less, something goes terribly wrong.

`gwf logs foo | less`

Gives the following output:

```
Traceback (most recent call last):
  File "/home/michaelk/anaconda/envs/gwf_conda/bin/gwf", line 6, in <module>
    sys.exit(gwf.cli.main())
  File "/home/michaelk/anaconda/envs/gwf_conda/lib/python3.6/site-packages/gwf-1.0b3-py3.6.egg/gwf/cli.py", line 216, in main
  File "/home/michaelk/anaconda/envs/gwf_conda/lib/python3.6/site-packages/gwf-1.0b3-py3.6.egg/gwf/cli.py", line 187, in run
  File "/home/michaelk/anaconda/envs/gwf_conda/lib/python3.6/site-packages/gwf-1.0b3-py3.6.egg/gwf/ext.py", line 88, in configure_extensions
  File "/home/michaelk/anaconda/envs/gwf_conda/lib/python3.6/site-packages/gwf-1.0b3-py3.6.egg/gwf/plugins/status.py", line 27, in configure
OSError: [Errno 22] Invalid argument
```

**Comment by dansondergaard** [comment]
Would you care to try with the most recent commit on master?

**Comment by dansondergaard** [comment]
The old plugin initialization was stupid and buggy, which is just I just rewrote it completely to use `click` and `click-plugins`. So this issue is probably solved on master (which is currently a mess because programming after 8pm is never a good idea).

**Comment by micknudsen** [comment]
Will try it out when you have a version compatible with Python 3.6. Latest commit on master fails to install due to flake8 requiring python<=3.5.

**Comment by dansondergaard** [comment]
As far as I can see there's no problem with Python 3.6, the build on Travis works fine:

https://travis-ci.org/mailund/gwf/jobs/225957673

Could you try again?

**Comment by micknudsen** [comment]
Good news: I can now install all dependencies using Python 3.6 in Anaconda.

Bad news: Have you changed the way templates must be defined?

```
  File "workflow.py", line 26, in <module>
    gwf.target(f'conda_trim_NORMAL_{lane}') << trim_paired_end_fastq(
TypeError: target() missing 2 required positional arguments: 'inputs' and 'outputs'
```

**Comment by mailund** [comment]
We made `inputs` and `outputs` required arguments at some point. That was a requirement to targets, not templates, and you really *should* always specify them. If you have templates that do not provide them, there must be something wrong with the template. I don't know if we have changed template specifications so you don't get empty lists for them automatically or something, but check if your `trim_paired_end_fastq` function actually has them in its spec.

**Comment by micknudsen** [comment]
Not sure what you mean. Here is what my template looks like:

```
def trim_paired_end_fastq(r1_file, r2_file, trimmed_r1_file, trimmed_r2_file, r1_trimming_report, r2_trimming_report):

    options = {

        'inputs': [r1_file, r2_file],
        'outputs': [trimmed_r1_file, trimmed_r2_file, r1_trimming_report, r2_trimming_report],
        'cores': 1,
        'memory': '4g',
        'walltime': '04:00:00'

    }

    spec = f'''

    # Blah blah blah

    '''

    return options, spec
```

This is called in the workflow as follows:

```

r1_file = 'foo'
...
r2_trimming_report = 'bar'

gwf.target('conda_trim') << trim_paired_end_fastq(

    r1_file=r1_file, r2_file=r2_file,
    trimmed_r1_file=trimmed_r1_file, trimmed_r2_file=trimmed_r2_file,
    r1_trimming_report=r1_trimming_report, r2_trimming_report=r2_trimming_report

)
```

Isn't that how it's supposed to be?

**Comment by dansondergaard** [comment]
Hm, this actually shows one of my biggest problems with how templates work right now. A target is created when gwf.target() is called and the template then modifies the target after creation. But this means that "inputs" and "outputs" *must* be optional in `gwf.target()`, which sucks.

So yeah, it's a mess right now because I wasn't sure how to solve this... Suggestions?

**Comment by dansondergaard** [comment]
Btw, @micknudsen, you're the best beta tester ever ;)

**Comment by mailund** [comment]
Indeed, that *is* how templates should be written -- and it would have worked earlier.

I guess the test for `inputs` and `outputs` is just in the wrong place...

@dansondergaard are you looking into this or should I?

**Comment by micknudsen** [comment]
I am having the day off today. You guys better fix this before I get back to work tomorrow! 😜

**Comment by mailund** [comment]
Since this is a separate issue from this one that relates to less, I will open it and have a look.

**Comment by dansondergaard** [comment]
@mailund You go crazy. The check should probably just be moved to `gwf.Graph`, but I don't really like that. We're basically going to check something that the language can check for us. But let's discuss in the new issue.

**Comment by micknudsen** [comment]
Works perfectly in latest commit on master.
