### ISSUE TITLE
Feature request: extra verbose

### ISSUE THREAD

**Issue by kaspermunch** [mailund/gwf#51]
An extra verbose flag that makes gwf print the options and bach commands for each target.

**Comment by kaspermunch** [comment]
Should I make new pull requests with each feature? BTW I can see that github rendering changed my comment. It was supposed to be:

list1 = ['some_dir/some_file.txt', 'some_dir/some_file.txt']
list2 = list1 <<tag>> 'foo’ <<outdir>> 'some_other_dir’ <<suffix>> '.fasta'
list3 = list2 <<tag>> 'bar'
list4 = list3 <<tag>> 'baz’ <<tag>> 'even_other_dir’ <<suffix>> '.bam'

I think it is a nice and clear way to produce new file paths.

On 23 Dec 2015, at 19:58, Thomas Mailund <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #51<https://github.com/mailund/gwf/issues/51>.

**Comment by mailund** [comment]
I have already split your pull request into different features and merged them into both develop and master.

That includes the infix operator feature, but I'm playing around with it now and might change the implementation slightly.

**Comment by mailund** [comment]
I think I like an implementation like this more:

```python
class infix_operator(object):
    def __init__(self, operator):
        self.operator = operator
        self.lhs = None
        self.rhs = None

    def __rlshift__(self, lhs):
        self.lhs = lhs
        return self

    def __rshift__(self, rhs):
        self.rhs = rhs
        return self.operator(self.lhs, self.rhs)

class list_operator(infix_operator):
    def __init__(self, operator):
        def listified_operator(lhs, rhs):
            return [operator(element, rhs) for element in lhs]
        self.operator = listified_operator
        self.lhs = None
        self.rhs = None
```

It does the same thing but it is easier to read than the lambda versions and it is a lot easier to define new operators because this can be done with simple adaptor as below (where I reuse the splice_path function you had although it is a bit more general than strictly needed for this):

```python
def splice_path(path, directory=None, suffix=None, tag=None):
    orig_dir, base_name = os.path.split(path)
    base_name, orig_suffix = os.path.splitext(base_name)
    if not directory:
        directory = orig_dir
    if not suffix:
        suffix = orig_suffix
    if tag:
        base_name = "{}_{}".format(tag, base_name)
    return os.path.join(directory, base_name) + suffix

@list_operator
def tag(lhs, rhs):
    return splice_path(lhs, tag = rhs)

@list_operator
def suffix(lhs, rhs):
    return splice_path(lhs, suffix=rhs)

@list_operator
def outdir(lhs, rhs):
    return splice_path(lhs, directory=rhs)
```

**Comment by kaspermunch** [comment]
Fint med mig. God jul i morgen.

--
Sent from my phone. Please excuse brevity and typos.

On 23. dec. 2015, at 21.51, Thomas Mailund <notifications@github.com<mailto:notifications@github.com>> wrote:


I think I like an implementation like this more:

class infix_operator(object):
    def __init__(self, operator):
        self.operator = operator
        self.lhs = None
        self.rhs = None

    def __rlshift__(self, lhs):
        self.lhs = lhs
        return self

    def __rshift__(self, rhs):
        self.rhs = rhs
        return self.operator(self.lhs, self.rhs)

class list_operator(infix_operator):
    def __init__(self, operator):
        def listified_operator(lhs, rhs):
            return [operator(element, rhs) for element in lhs]
        self.operator = listified_operator
        self.lhs = None
        self.rhs = None

It does the same thing but it is easier to read than the lambda versions and it is a lot easier to define new operators because this can be done with simple adaptor as below (where I reuse the splice_path function you had although it is a bit more general than strictly needed for this):

def splice_path(path, directory=None, suffix=None, tag=None):
    orig_dir, base_name = os.path.split(path)
    base_name, orig_suffix = os.path.splitext(base_name)
    if not directory:
        directory = orig_dir
    if not suffix:
        suffix = orig_suffix
    if tag:
        base_name = "{}_{}".format(tag, base_name)
    return os.path.join(directory, base_name) + suffix

@list_operator
def tag(lhs, rhs):
    return splice_path(lhs, tag = rhs)

@list_operator
def suffix(lhs, rhs):
    return splice_path(lhs, suffix=rhs)

@list_operator
def outdir(lhs, rhs):
    return splice_path(lhs, directory=rhs)

**Comment by mailund** [comment]
I lige m�de
