### ISSUE TITLE
GWF organization on GitHub?

### ISSUE THREAD

**Issue by dansondergaard** [mailund/gwf#78]
Should we have a GitHub organization to contain the various subprojects of GWF?

**Comment by dansondergaard** [comment]
It's essentially a user, e.g. Google has a "Google" organization on GitHub for all Google projects: https://github.com/google

**Comment by mailund** [comment]
If you think it is a good idea, then sure. I don't know if it is really needed for a single project, but no complaints from me.

**Comment by dansondergaard** [comment]
We probably want to have separate repositories for the "official" plugins, but it's not urgent in any way right now :-)
