### ISSUE TITLE
Performance command

### ISSUE THREAD

**Issue by micknudsen** [mailund/gwf#79]
The current implementation of --performance sucks (and I am to blame). It relies on the third-party `jobinfo` script. Should be based on `sacct` instead.

**Comment by dansondergaard** [comment]
True, true and true ;) However, we will be moving functionality like this out of the core of gwf and into plugins/extensions/whatever. You can have a go at rewriting code for --performance when a plugin system is in place.

**Comment by mailund** [comment]
I have added @micknudsen as a collaborator on the project so he can commit changes. Please don't abuse this :)

It is probably best if all changes are made through a pull request but now you should both be able to accept requests if I am not around.

**Comment by dansondergaard** [comment]
For some reason I cannot assign @micknudsen to this issue. Why, oh why, GitHub?

**Comment by micknudsen** [comment]
Because I left the project.

**Comment by dansondergaard** [comment]
Well, you're assigned to this issue anyway ;)

**Comment by dansondergaard** [comment]
This will be implemented as a standalone plugin. See [this](https://github.com/dansondergaard/gwf-slurm-utilization) repository.
