### ISSUE TITLE
Importing modules from workflow.py

### ISSUE THREAD

**Issue by ymer** [mailund/gwf#88]
When importing modules from workflow.py it doesn't look in the directory where workflow.py is located. This makes it complicated to share modules between workflow.py and other scripts.

**Comment by dansondergaard** [comment]
Can you elaborate on this? gwf loads modules like any other Python script, so if `a.py` contains:

```
import b
```

and `b.py` is an empty Python module, `b.py` should be imported (I just tested this on version 2.7.11).

Can you provide a minimal example that fails? Also, what does your `$PYTHONPATH` contain?

**Comment by mailund** [comment]
I think the problem is that the workflow directory is not in PYTHON_PATH. Current working dir is if you call Python but not if you call gwf.

**Comment by dansondergaard** [comment]
Should we add the current working dir to the Python path in gwf, or should we let it be up to the user?

**Comment by mailund** [comment]
I think we should add it, so it works the same way as calling "python workflow.py"
