### ISSUE TITLE
Fast overview of the status of the processes of the workflow.

### ISSUE THREAD

**Issue by ymer** [mailund/gwf#89]
The -s command is extremely slow with many processes.

Something like this would be very useful:
> gwf -s2

COMPLETED
job1
job2
job3

PENDING
job4
job5
job7

CANCELLED
job6

RUNNING
job8
Job9

COMPLETED 3
PENDING 3
CANCELLED 1
RUNNING 2

**Comment by dansondergaard** [comment]
Thank you for your suggestion.

Speeding up things like this is definitely on our todo list, but it probably won't be before 1.0.0 since we are in the midst of a major rewrite of gwf (to accommodate enhancements like this).

**Comment by dansondergaard** [comment]
Closing this issue in favour of #66.
