### ISSUE TITLE
input is a built-in function

### ISSUE THREAD

**Issue by ymer** [mailund/gwf#91]
The 'input' keyword is used when defining targets. It is customary in python to avoid overshadowing built-in functions.

**Comment by dansondergaard** [comment]
You're right about the best practice, but in this case it's not shadowing the builtin `input` since it's a function argument.

```
>>> def foo(input=42):
...     return input
... 
>>> foo(input=10)
10
>>> answer = input('bar: ') # input has not been overriden, works as usual.
bar: # waits for input.
```

**Comment by ymer** [comment]
A factor is also that python editors color code it annoyingly:

![example](https://cloud.githubusercontent.com/assets/3323314/17304264/b190c032-581c-11e6-83ef-90773276ffd2.png)

**Comment by dansondergaard** [comment]
That's a good point. My editor (Atom) highlights the snippet correctly. So I guess this is more of a syntax highlighting/editor issue.

I think it would be pretty confusing to rename `input` to something else, after all, it's a pretty good name in this case.

**Comment by mailund** [comment]
It would break all existing workflows. It is really too late to change now

**Comment by dansondergaard** [comment]
I agree, there's no real benefit to changing it and changing it would break a lot of existing workflows.
