### ISSUE TITLE
Spaces in target name

### ISSUE THREAD

**Issue by ymer** [mailund/gwf#95]
Spaces in target names are not allowed. An invisible space at the end of a target name resulted in the following error message:

"Submitting target gene_analysis.height  ... Can't open script file '/home/jpal/magma_workflow/.scripts/gene_analysis.height': No such file or directory at /com/extra/slurm/14.03.0/bin/qsub line 241, <DATA> line 608."

It would be preferable with an error message such as:

'target 'gene_analysys.height ': spaces are not allowed in target names'

**Comment by mailund** [comment]
Maybe we should just quote spaces. We quote other characters.

**Comment by dansondergaard** [comment]
I never use spaces in target names since I think it's ugly, but quoting would solve it, yes.

**Comment by dansondergaard** [comment]
Actually, I think it's better to only allow [a-zA-Z0-9.-_] in target and workflow names. Something like:

```python
In [23]: def valid_name(candidate):
    ...:     return True if re.match(r'^[a-zA-Z_][a-zA-Z0-9._]*$', candidate) is not None else False
    ...:     
    ...: 

In [24]: valid_name('whale')
Out[24]: True

In [25]: valid_name('whale5')
Out[25]: True

In [26]: valid_name('whale.5')
Out[26]: True

In [27]: valid_name('whale.5_1')
Out[27]: True

In [28]: valid_name('5.1_whale')
Out[28]: False

In [29]: valid_name('5whale')
Out[29]: False
```

Disallowing numbers at the beginning of names means that we can (if necessary in the future) easily make target names valid Python names. An appropriate error message should be shown if a target has an invalid name. Would this be a solution for you, @ymer? @mailund?
